Backend: Vivado
KerasJson: hard_sigmoid.json
KerasH5: hard_sigmoid.h5
OutputDir: my-Catapult-test
ProjectName: hard_sigmoid
XilinxPart: xcku115-flvb2104-2-i
Part: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType : io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16, 6>
    ReuseFactor: 1
    Strategy: Latency
