Backend: Catapult
KerasJson: selu.json
KerasH5: selu_weights.h5
OutputDir: my-Catapult-test
ProjectName: selu
XilinxPart: xcku115-flvb2104-2-i
Part: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType : io_serial
HLSConfig:
  Model:
    Precision: ap_fixed<16, 6>
    ReuseFactor: 1
    Strategy: Latency
