KerasJson: dense.json
KerasH5:   dense_weights.h5
OutputDir: my-Vivado-test
ProjectName: myproject
Part: xcku115-flvb2104-2-i
XilinxPart: xcku115-flvb2104-2-i
InputData: tb_data/tb_input_features.dat
OutputPredictions: tb_data/tb_output_predictions.dat
ClockPeriod: 5
Backend: Vivado
IOType: io_stream

HLSConfig:
    Model:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Strategy: Latency
    LayerName:
      softmax:
        Precision: ap_ufixed<16,6>
        ReuseFactor: 1
        Strategy: Stable
        exp_table_t: ap_fixed<18,8>
        inv_table_t: ap_fixed<18,4>
        table_size: 1024
      Dense1_input:
        Precision:
          result: ap_fixed<16,6>
      relu1:
        Precision:
          result: ap_fixed<7,1>
        ReuseFactor: 1
      Dense2_input:
        Precision:
          result: ap_fixed<16,6>
      Dense1:
        Precision:
          bias: ap_fixed<6,1>
          weight: ap_fixed<6,1>
        ReuseFactor: 1
        Strategy: Latency
      Dense2:
        Precision:
          bias: ap_fixed<6,1>
          weight: ap_fixed<6,1>
        ReuseFactor: 1
        Strategy: Latency