stages:
  - generate
  - trigger
  - test
  - gather

generator:
  stage: generate
  image: python:3.7-alpine
  tags: 
    - docker
  before_script:
    - pip install pyyaml
  script: 
    - cd test/pytest
    - python generate_ci_yaml.py
  artifacts:
    paths:
      - test/pytest/pytests.yml

pytests:
  stage: trigger
  trigger:
    include:
      - local: test/pytest/ci-template.yml
      - artifact: test/pytest/pytests.yml
        job: generator
    strategy: depend

coverage:
  stage: gather
  image: python:3.7-alpine
  tags:
    - docker
  before_script:
    - pip install coverage
  script:
    - cd test/pytest
    - coverage combine test*.coverage
    - coverage report
    - coverage xml 
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: test/pytest/coverage.xml