Backend: Catapult
KerasJson: leaky_relu.json
KerasH5: leaky_relu_weights.h5
OutputDir: my-Catapult-test
ProjectName: leaky_relu
XilinxPart: xcku115-flvb2104-2-i
Part: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType : io_stream
HLSConfig:
  Model:
    Precision: ap_fixed<16, 6>
    ReuseFactor: 1
    Strategy: Latency
