Backend: Catapult
KerasJson: relu.json
KerasH5: relu_weights.h5
OutputDir: my-Catapult-test
ProjectName: relu
XilinxPart: xcku115-flvb2104-2-i
Part: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType : io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16, 6>
    ReuseFactor: 1
    Strategy: Latency
