Pyconfig:
  layername: test
  layerlongname: Addons>InstanceNormalization
  outputshape: 0
  attrlist:
    Attribute:
    - n_filt
    - epsilon
    - ops
    WeightAttribute:
    - gamma
    - beta
    TypeAttribute:
    - gamma
    - beta
  genattrtypes:
  - int
  - float
  - str
  genattrdef:
  - -1
  - 0.001
  - "\"ap_fixed<32,10>\""
  otherargs:
  - gamma
  - beta
  - epsilon
  attrdef:  |
    if len(input_shapes[0]) == 2:
        layer['n_filt'] = -1
    elif len(input_shapes[0]) == 3:
        layer['n_filt'] = input_shapes[0][2]
    elif len(input_shapes[0]) == 4:
        layer['n_filt'] = input_shapes[0][3]
Cconfig:
  - asd
