{'Backend': 'Vivado', 
 'ClockPeriod': 100,
 'HLSConfig': {'Model': {'Precision': 'ap_fixed<8,0>', 'ReuseFactor': 1}},
 'IOType': 'io_stream', 
 'KerasH5': 'qkeras/FashionMNIST_weights.h5',
 'KerasJson': 'qkeras/fashionmnist_model2.json',
 'OutputDir': 'my-ccs-test-stream', 
 'ProjectName': 'myproject', 
 'Part': 'xcku115-flvb2104-2-i', 
 'XilinxPart': 'xcku115-flvb2104-2-i'}
